### PR TITLE
Fixing dependencies for API compatibility

### PR DESCRIPTION
**Pull request by bendilley**
Proposed fix for Issue #86

Current cucumber-nagios is not yet compatible with the latest versions
of cucumber, mechanize and amqp. Limiting version dependencies to known
compatible ones for now, until further development takes place.

I've committed changes to Gemfile.lock, though some suggest it shouldn't
be included in the repo for a gem.
(ref http://stackoverflow.com/a/4151540/418602)

### CODE REVIEW

**Comment by bendilley** [comment]
I've added a commit which allows the formatter to be used with ruby 1.8; hope that's ok.

**Comment by zeph** [comment]
fixed???? (this from installing ur repo via "gem specific_install -l https://github.com/auxesis/cucumber-nagios.git")

> ERROR:  While executing gem ... (Gem::DependencyError)
>     Unable to resolve dependencies: cucumber-nagios requires net-ssh (>= 2.1.4); vagrant requires net-ssh (~> 2.1.4); net-scp requires net-ssh (>= 1.99.1); chef requires net-ssh (~> 2.2.2); net-ssh-multi requires net-ssh (>= 2.1.4); net-ssh-gateway requires net-ssh (>= 2.6.5)

**Comment by palominoz** [comment]
The available version of this gem in repository seems to be still buggy

**Comment by thorrsson** [comment]
Why does cucumber-nagios now depend on Chef?

**Pull request merged**
