### PR TITLE
Cucumber-nagios doesn't play nice with bundler 1.0.8+

### PR DESCRIPTION
**Pull request by josephholsten**
Given I have the cucumber-nagios 0.8.10 gem installed
And I have the bundler 1.0.10 gem installed
When I run "cucumber-nagios-gen project tmp; cd tmp; bundle install"
And I run "cd tmp; bundle show cucumber-nagios"
Then the output should contain "cucumber-nagios-0.8.10"
And the output should not contain "cucumber-nagios-0.6.8"

This seems to be due to an exact gem dependency on bundler 1.0.7. Changing the dependency to ~>1.0.7 works fine.

### CODE REVIEW

**Comment by auxesis** [comment]
For maintainability sanity, I'm keen on locking exact versions of cucumber-nagios to exact dependencies. 

I totally get the `~>` operator and what it's meant to do, I've just been bitten in the past by other gem maintainers not respecting it and breaking things between minor releases (Webrat, I'm looking at you *death stare*). 

I'm happy to give this a go and see where it takes us.

**Comment by josephholsten** [comment]
I totally understand about the exact dependencies. Even `~>` isn't a cure all, as I discovered with vagrant and cucumber.

It's normally possible to call out a specific version when running a gem, as in `bundle _1.0.7_ help`, so it's probably worth mentioning that in the README. Of course, bundler <= 1.0.9 don't work with rubygems 1.5, so I've got to use rvm to make that work.

If you can live without rubygems 1.5 support, I'll drop this and rework my other patches.

**Comment by auxesis** [comment]
Closing in favour of #45.

**Comment by zeph** [comment]
Hi, can we reopen this issue? Using rvm with cucumber-nagios is getting impossible since:
- rvm installs automatically bundler 1.1.3, and 3 other gems by default
- in particular, with ruby 1.9.2 and 1.9.3, bundler 1.0.7 doesn't seem to work 
  (so, removing bundler 1.1.3 in favour of 1.0.7 is not helping)

Is there any plan to evaluate or fix the dependancies to be able to work with an up-to-date version of Bundler?

best regards,

**Comment by zeph** [comment]
with up to date...

```
Bundler could not find compatible versions for gem "bundler":
  In Gemfile:
    cucumber-nagios (>= 0) ruby depends on
      bundler (~> 1.0.7) ruby

  Current Bundler version:
    bundler (1.1.3)

This Gemfile requires a different version of Bundler.
Perhaps you need to update Bundler by running `gem install bundler`?
```

with 1.0.7 ... 

```
/Users/zeph/.rvm/gems/ruby-1.9.2-p320@global/gems/bundler-1.0.7/lib/bundler/ui.rb:56:in `<class:UI>': uninitialized constant Gem::SilentUI (NameError)
    from /Users/zeph/.rvm/gems/ruby-1.9.2-p320@global/gems/bundler-1.0.7/lib/bundler/ui.rb:2:in `<module:Bundler>'
    from /Users/zeph/.rvm/gems/ruby-1.9.2-p320@global/gems/bundler-1.0.7/lib/bundler/ui.rb:1:in `<top (required)>'
    from /Users/zeph/.rvm/gems/ruby-1.9.2-p320@global/gems/bundler-1.0.7/lib/bundler/cli.rb:16:in `initialize'
    from /Users/zeph/.rvm/gems/ruby-1.9.2-p320@global/gems/bundler-1.0.7/lib/bundler/vendor/thor.rb:246:in `new'
    from /Users/zeph/.rvm/gems/ruby-1.9.2-p320@global/gems/bundler-1.0.7/lib/bundler/vendor/thor.rb:246:in `dispatch'
    from /Users/zeph/.rvm/gems/ruby-1.9.2-p320@global/gems/bundler-1.0.7/lib/bundler/vendor/thor/base.rb:389:in `start'
    from /Users/zeph/.rvm/gems/ruby-1.9.2-p320@global/gems/bundler-1.0.7/bin/bundle:13:in `<top (required)>'
    from /Users/zeph/.rvm/gems/ruby-1.9.2-p320@global/bin/bundle:23:in `load'
    from /Users/zeph/.rvm/gems/ruby-1.9.2-p320@global/bin/bundle:23:in `<main>'
make: *** [gems] Error 1
```

**Pull request closed without merging**
